### ISSUE TITLE
Neo4j container fails to start

### ISSUE THREAD

**Issue by eidens** [source-data/sd-graph#17]
The neo4j container fails to start since a few days, both locally and on the db deployment server. Here's the error that shows up locally when running `docker-compose -f production.yml up neo4j`:

```
ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address. Error starting Neo4j database server at /data/databases
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@2eadc9f6' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
	... 5 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:576)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.neo4j.procedure.impl.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:160)
	at org.neo4j.procedure.impl.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:138)
	at org.neo4j.collection.AbstractPrefetchingRawIterator.peek(AbstractPrefetchingRawIterator.java:50)
	at org.neo4j.collection.AbstractPrefetchingRawIterator.hasNext(AbstractPrefetchingRawIterator.java:36)
	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:111)
	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:85)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.start(GlobalProceduresRegistry.java:342)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	... 7 more
2021-10-03 14:19:09.301+0000 INFO  Neo4j Server shutdown initiated by request
```

The important part is probably `Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@2eadc9f6' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".`, which indicates that it might be a problem with our plugins (that's what the GlobalProceduresRegistry class seems to be for).

**Comment by eidens** [comment]
This exact error has ocurred before, but without resolution: https://github.com/neo4j/neo4j/issues/12730

**Comment by eidens** [comment]
When run locally, downgrading to neo4j:4.0 (in my case, `neo4j/neo4j-arm64-experimental:4.0.12-arm64`) or upgrading to 4.3 (4.3.5 for the arm64 image) removes the error.

When upgrading to 4.3 the database has to be migrated, though.

Here's the table of neo4j & corresponding plugin versions:

| neo4j | apoc | graph-data-science | n10s | Starts up? |
| -- | -- | -- | -- | -- |
| 4.3.5 | 4.3.0.3 | 1.7.0 | 4.3.0.1 | ✅ |
| 4.1.10 | 4.1.0.10 | 1.7.0 | 4.1.0.1 | ❌ |
| 4.0.12 | 4.0.0.18 | 1.6.5 | 4.0.0.1 | ✅ |

**Comment by eidens** [comment]
After narrowing down the possible causes: only the combination of neo4j:4.1 with both apoc and n10s as plugins produces this error.

Since we're not using n10s at all, we can just remove it and don't have to up- or downgrade neo4j.
